import { db } from '@/db';
import { conversationHistory } from '@/db/schema';

async function main() {
    const sampleConversations = [
        {
            userId: 1,
            workspaceId: 1,
            sessionId: 'sess_a1b2c3d4e5f6',
            message: 'What are your business hours?',
            intent: 'business_hours_inquiry',
            entities: {},
            sentiment: 'neutral',
            response: 'Our business hours are Monday to Friday, 9 AM to 6 PM EST. We\'re also available on Saturday from 10 AM to 4 PM. How else can I help you today?',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 3 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            workspaceId: 2,
            sessionId: 'sess_g7h8i9j0k1l2',
            message: 'I need help with my order #12345',
            intent: 'order_support',
            entities: { order_id: '12345' },
            sentiment: 'negative',
            response: 'I\'d be happy to help you with order #12345. Let me pull up the details for you. It looks like your order is currently in transit and should arrive by tomorrow. Would you like tracking information?',
            createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 1 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 3,
            workspaceId: 3,
            sessionId: 'sess_m3n4o5p6q7r8',
            message: 'Can you recommend a good laptop for programming?',
            intent: 'product_recommendation',
            entities: { product_category: 'electronics', use_case: 'programming' },
            sentiment: 'positive',
            response: 'For programming, I\'d recommend our MacBook Pro M3 or the Dell XPS 15. Both have excellent processing power, plenty of RAM, and great displays. The MacBook is ideal if you work in the Apple ecosystem, while the Dell offers more customization options. What\'s your budget range?',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            workspaceId: 1,
            sessionId: 'sess_s9t0u1v2w3x4',
            message: 'My payment failed but money was deducted from my account',
            intent: 'payment_issue',
            entities: { issue_type: 'payment_failure' },
            sentiment: 'frustrated',
            response: 'I\'m sorry to hear about this payment issue. This is concerning and I want to help resolve it immediately. Can you please provide your transaction reference number? In the meantime, I\'m escalating this to our payment team who will investigate within the next 2 hours.',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 4,
            workspaceId: 4,
            sessionId: 'sess_y5z6a7b8c9d0',
            message: 'Do you offer international shipping?',
            intent: 'shipping_inquiry',
            entities: { shipping_type: 'international' },
            sentiment: 'neutral',
            response: 'Yes, we offer international shipping to over 150 countries! Shipping costs and delivery times vary by destination. You can enter your address at checkout to see available options and estimated delivery dates. Most international orders arrive within 7-14 business days.',
            createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 5,
            workspaceId: 5,
            sessionId: 'sess_e1f2g3h4i5j6',
            message: 'How do I return an item?',
            intent: 'return_request',
            entities: {},
            sentiment: 'neutral',
            response: 'Our return policy allows returns within 30 days of purchase. To start a return: 1) Log into your account, 2) Go to Order History, 3) Select the item you want to return, 4) Choose a reason and print the prepaid return label. You\'ll receive a full refund once we receive the item. Is there a specific order you\'d like to return?',
            createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            workspaceId: 2,
            sessionId: 'sess_k7l8m9n0o1p2',
            message: 'What\'s the difference between the Pro and Basic plans?',
            intent: 'plan_comparison',
            entities: { plan_types: ['pro', 'basic'] },
            sentiment: 'positive',
            response: 'Great question! The Basic plan includes core features and 5GB storage for $9.99/month. The Pro plan adds advanced analytics, 50GB storage, priority support, and team collaboration features for $29.99/month. Pro users also get early access to new features. Which features are most important to you?',
            createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 3,
            workspaceId: 3,
            sessionId: 'sess_q3r4s5t6u7v8',
            message: 'I forgot my password',
            intent: 'account_access',
            entities: { issue_type: 'password_reset' },
            sentiment: 'neutral',
            response: 'No problem! I can help you reset your password. Click on "Forgot Password" on the login page, enter your email address, and you\'ll receive a password reset link within a few minutes. Make sure to check your spam folder if you don\'t see it. Let me know if you need any other assistance!',
            createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            workspaceId: 1,
            sessionId: 'sess_w9x0y1z2a3b4',
            message: 'Is there a student discount available?',
            intent: 'discount_inquiry',
            entities: { discount_type: 'student' },
            sentiment: 'positive',
            response: 'Yes! We offer a 20% student discount on all our plans. You\'ll need to verify your student status through our partner platform. Just sign up with your .edu email address and follow the verification steps. The discount is automatically applied to your account. Are you currently a student?',
            createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 4,
            workspaceId: 4,
            sessionId: 'sess_c5d6e7f8g9h0',
            message: 'The app keeps crashing on my phone',
            intent: 'technical_support',
            entities: { issue_type: 'app_crash', device_type: 'mobile' },
            sentiment: 'frustrated',
            response: 'I apologize for the inconvenience. Let\'s troubleshoot this together. First, try clearing the app cache and restarting your phone. If that doesn\'t work, uninstall and reinstall the app. Make sure you\'re running the latest version (v2.1.5). What phone model and OS version are you using?',
            createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 5,
            workspaceId: 5,
            sessionId: 'sess_i1j2k3l4m5n6',
            message: 'Can I upgrade my plan mid-cycle?',
            intent: 'plan_upgrade',
            entities: { action_type: 'upgrade' },
            sentiment: 'positive',
            response: 'Absolutely! You can upgrade your plan at any time. When you upgrade, you\'ll be charged a prorated amount for the remainder of your billing cycle. The new features will be available immediately. Would you like me to walk you through the upgrade process?',
            createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            workspaceId: 2,
            sessionId: 'sess_o7p8q9r0s1t2',
            message: 'Where can I track my order?',
            intent: 'order_tracking',
            entities: {},
            sentiment: 'neutral',
            response: 'You can track your order in several ways: 1) Log into your account and go to Order History, 2) Use the tracking link sent to your email, or 3) Enter your order number on our Track Order page. You\'ll see real-time updates including estimated delivery. Do you have your order number handy?',
            createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 3,
            workspaceId: 3,
            sessionId: 'sess_u3v4w5x6y7z8',
            message: 'This product is amazing! Best purchase ever!',
            intent: 'positive_feedback',
            entities: {},
            sentiment: 'positive',
            response: 'Thank you so much for the wonderful feedback! We\'re thrilled to hear you\'re enjoying your purchase. Comments like yours make our day! Would you mind leaving a review on our website? It really helps other customers make informed decisions.',
            createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 1,
            workspaceId: 1,
            sessionId: 'sess_a9b0c1d2e3f4',
            message: 'Do you have a mobile app?',
            intent: 'product_inquiry',
            entities: { product_type: 'mobile_app' },
            sentiment: 'neutral',
            response: 'Yes! We have mobile apps for both iOS and Android. You can download them from the App Store or Google Play Store. The mobile app includes all the features of the web version, plus push notifications and offline mode. Let me know if you need help getting started!',
            createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 4,
            workspaceId: 4,
            sessionId: 'sess_g5h6i7j8k9l0',
            message: 'Can I get a refund for my subscription?',
            intent: 'refund_request',
            entities: { request_type: 'subscription_refund' },
            sentiment: 'negative',
            response: 'I understand you\'d like a refund. We offer refunds within 14 days of purchase if you\'re not satisfied. Since you\'re within that window, I can process this for you. May I ask what led to this decision? Your feedback helps us improve. The refund will be processed to your original payment method within 5-7 business days.',
            createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(conversationHistory).values(sampleConversations);
    
    console.log('✅ Conversation history seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});